language: node_js
node_js:
  - '8'
before_script:
  - python -m SimpleHTTPServer & sleep 2
script:
  - yarn lint
  - yarn test
  - yarn test-webpack http://localhost:8000/test/browser/run-mocha.html

